import { routePaths } from "./copy";

export const obfuscationConfig = {
  enable: process.env.NODE_ENV === "production",
  autoExcludeNodeModules: true,
  threadPool: true,
  log: false,
  options: {
    compact: true,

    controlFlowFlattening: false,
    controlFlowFlatteningThreshold: 0,
    deadCodeInjection: false,
    deadCodeInjectionThreshold: 0,
    debugProtection: false,
    debugProtectionInterval: 0,
    disableConsoleOutput: true,

    identifierNamesGenerator: "hexadecimal" as const,

    selfDefending: false,
    simplify: false,

    splitStrings: false,
    splitStringsChunkLength: 0,
    stringArray: false,
    stringArrayCallsTransform: false,
    stringArrayCallsTransformThreshold: 0,
    stringArrayEncoding: [],
    stringArrayIndexShift: false,
    stringArrayRotate: false,
    stringArrayShuffle: false,
    stringArrayWrappersCount: 0,
    stringArrayWrappersChainedCalls: false,
    stringArrayWrappersParametersMaxCount: 2,
    stringArrayWrappersType: "variable" as const,
    stringArrayThreshold: 0,

    transformObjectKeys: false,
    unicodeEscapeSequence: false,
    numbersToExpressions: false,

    renameGlobals: false,
    renameProperties: false,

    ignoreImports: true,
    seed: Math.floor(Math.random() * 100000),
    sourceMap: false,
    target: "browser" as const,
  },
  exclude: [
    "**/node_modules/**",
    `**/${routePaths.scramjet}/**`,
    `**/${routePaths.epoxy}/**`,
    `**/${routePaths.libcurl}/**`,
    `**/${routePaths.baremux}/**`,
    `**/${routePaths.reflux}/**`,
    `**/core/inspect.js`,
    "**/ob-fonts.js",
    "**/poppins-obf*.json",
    "**/vendor-*.js",
    "**/chunks/vendor*.js",
    "**/*.css",
    "**/*.json",
    "**/*.woff2",
    "**/*.ttf",
    "**/*.png",
    "**/*.jpg",
    "**/*.svg",
    "**/*.gif",
    "**/*.webp",
    "**/*.mp4",
    "**/*.webm",
    "**/*.ogg",
    "**/*.mp3",
    "**/*.wav",
    "**/*.flac",
    "**/*.aac",
    "**/*.eot",
    "**/*.otf",
    "**/*.woff",
    "**/*.ico",
    "**/*.pdf",
  ],
};
