import type { ExtensionContext } from '../../extfs/types';
import { ChromeDownloadsBase } from '../../shared';

export class ChromeDownloads extends ChromeDownloadsBase {
  constructor(ctx: ExtensionContext) {
    super(ctx);
  }

  static readonly InterruptReason = {
    CRASH: "CRASH",
    FILE_ACCESS_DENIED: "FILE_ACCESS_DENIED",
    FILE_BLOCKED: "FILE_BLOCKED",
    FILE_BLOCKED_BY_APPLICATION_GUARD: "FILE_BLOCKED_BY_APPLICATION_GUARD",
    FILE_FAILED: "FILE_FAILED",
    FILE_HASH_MISMATCH: "FILE_HASH_MISMATCH",
    FILE_NAME_TOO_LONG: "FILE_NAME_TOO_LONG",
    FILE_NO_SPACE: "FILE_NO_SPACE",
    FILE_SAME_AS_SOURCE: "FILE_SAME_AS_SOURCE",
    FILE_SECURITY_CHECK_FAILED: "FILE_SECURITY_CHECK_FAILED",
    FILE_TOO_LARGE: "FILE_TOO_LARGE",
    FILE_TOO_SHORT: "FILE_TOO_SHORT",
    FILE_TRANSIENT_ERROR: "FILE_TRANSIENT_ERROR",
    FILE_VIRUS_INFECTED: "FILE_VIRUS_INFECTED",
    NETWORK_DISCONNECTED: "NETWORK_DISCONNECTED",
    NETWORK_FAILED: "NETWORK_FAILED",
    NETWORK_INVALID_REQUEST: "NETWORK_INVALID_REQUEST",
    NETWORK_SERVER_DOWN: "NETWORK_SERVER_DOWN",
    NETWORK_TIMEOUT: "NETWORK_TIMEOUT",
    SERVER_BAD_CONTENT: "SERVER_BAD_CONTENT",
    SERVER_CERT_PROBLEM: "SERVER_CERT_PROBLEM",
    SERVER_CONTENT_LENGTH_MISMATCH: "SERVER_CONTENT_LENGTH_MISMATCH",
    SERVER_CROSS_ORIGIN_REDIRECT: "SERVER_CROSS_ORIGIN_REDIRECT",
    SERVER_FAILED: "SERVER_FAILED",
    SERVER_FORBIDDEN: "SERVER_FORBIDDEN",
    SERVER_NO_RANGE: "SERVER_NO_RANGE",
    SERVER_UNAUTHORIZED: "SERVER_UNAUTHORIZED",
    SERVER_UNREACHABLE: "SERVER_UNREACHABLE",
    USER_CANCELED: "USER_CANCELED",
    USER_SHUTDOWN: "USER_SHUTDOWN",
  } as const;
}
